In [1]:
import numpy as np

In [2]:
print('Задание 1')
N = int(input())
a = np.arange(N-1, -1, -1)
print(a)

Задание 1
10
[9 8 7 6 5 4 3 2 1 0]


In [3]:
print('Задание 2')
N = int(input())
b = np.diag(a, k=0)
print(b)
print(a.sum())

Задание 2
10
[[9 0 0 0 0 0 0 0 0 0]
 [0 8 0 0 0 0 0 0 0 0]
 [0 0 7 0 0 0 0 0 0 0]
 [0 0 0 6 0 0 0 0 0 0]
 [0 0 0 0 5 0 0 0 0 0]
 [0 0 0 0 0 4 0 0 0 0]
 [0 0 0 0 0 0 3 0 0 0]
 [0 0 0 0 0 0 0 2 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]]
45


In [4]:
print('Задание 3')
valuesL = np.array([
    [4, 2, 1],
    [1, 3, 0],
    [5, 4, 0]
            ])
valuesR = np.array([4, 12, -3])
print(np.allclose( np.dot(valuesL, np.linalg.solve(valuesL, valuesR)), valuesR))
print(np.linalg.solve(valuesL, valuesR))

Задание 3
True
[-5.18181818  5.72727273 13.27272727]


In [5]:
print('Задание 4')
next_user_stats = np.array([0, 1, 2, 0, 0, 0])
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)
temp = users_stats.reshape(1,60).reshape(60)
num_of_users = users_stats.shape[0]
length_of_array = len(next_user_stats)
new_user_stats = temp[ :length_of_array]
i = 0
values = list()
def cosine( a, b ):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    aLength = np.linalg.norm( next_user_stats )
    bLength = np.linalg.norm( new_user_stats  )
    return np.dot( a, b ) / ( aLength * bLength )

while i != num_of_users:
    new_user_stats = temp[ :length_of_array]
    values.append( cosine( next_user_stats, new_user_stats ) )
    temp = temp[length_of_array:] 
    i += 1

print(f'User ID - {values.index(max(values))}')

Задание 4
User ID - 7
